#!/bin/bash

export CRITTER_MECHANISM=1
export CRITTER_AUTOTUNING_MODE=1
export CRITTER_COMM_ENVELOPE_PARAM=1
export CRITTER_COMM_UNIT_PARAM=3
export CRITTER_COMM_ANALYSIS_PARAM=1
export CRITTER_COMP_ENVELOPE_PARAM=0
export CRITTER_COMP_UNIT_PARAM=3
export CRITTER_COMP_ANALYSIS_PARAM=1
export CRITTER_PATTERN_ERROR_LIMIT=0.5
export CRITTER_PATTERN_TIME_LIMIT=0.001
export CRITTER_PATTERN_COUNT_LIMIT=5
export CRITTER_CONDITIONAL_PROPAGATION=1
#export CRITTER_UPDATE_ANALYSIS=1
#export CRITTER_TRACK_COLLECTIVE=1
#export CRITTER_TRACK_P2P=1
#export CRITTER_SCHEDULE_KERNELS=1
