#!/bin/bash

echo "[script name]  [number of nodes]  [processor per node]  [number of binaries to test on] [number of hours for run]"
echo "[number of minutes for run]  [number of seconds for run]"
echo "For each of the [number of binaries to test on], you must specify:"
echo "  [binary path and name]"
echo "  Binary Tag (MM3D, CFR3D, CholeskyQR2_1D, CholeskyQR2_3D, Cholesky_QR2_Tunable, scaLAPACK_QR)"
echo "  [number of iterations for each specific run]"
echo "  [number of processors to start] [number of processors to end] [jump amount] [jump operator (+,-,*,/]"
echo "  [dimension m to start] [dimension m to end] [jump amount] [jump operator (+,-,*,/]"
echo "  if not CFR3D, specify: [dimension n to start] [dimension n to end] [jump amount] [jump operator (+,-,*,/]"
echo "    Based on Binary Tag, more options are available."
echo "    If Binary Tag == MM3D, specify: [dimension k to start] [dimension k to end] [jump amount] [jump operator (+,-,*,/]"
echo "    If Binary Tag == CFR3D, specify: [number of powers of 2 greater than the theoretically optimal base case]"
echo "    If Binary Tag == CholeskyQR2_1D, specify: nothing is needed"
echo "    If Binary Tag == CholeskyQR2_3D, specify: nothing is needed"
echo "    If Binary Tag == CholeskyQR2_Tunable, specify: [processor grid dimension d to start] [processor grid dimension d to end] [jump amount] [jump operator (+,-,*,/]"
echo "    						 [processor grid dimension c to start] [processor grid dimension c to end] [jump amount] [jump operator (+,-,*,/]"
echo "    If Binary Tag == scaLAPACK_QR, specify:        [blocksize to start] [blocksize to end] [jump amount] [jump operator (+,-,*,/]"
echo "    						 [number of processor rows to start] [number of processor rows to end] [jump amount] [jump operator (+,-,*,/]"
