#!/bin/bash

export MKL_NUM_THREADS=1

export CRITTER_MODE=1
export CRITTER_MECHANISM=1
#export CRITTER_SCHEDULE_TAG=cholinv
export CRITTER_AUTOTUNING_TEST=1

export CRITTER_DECOMPOSITION_COMP_REPLACE=1
export CRITTER_DECOMPOSITION_COMM_REPLACE=1

export CRITTER_AUTOTUNING_COMM_STATE_AGGREGATION_MODE=0
export CRITTER_AUTOTUNING_COMP_STATE_AGGREGATION_MODE=0

export CRITTER_COMP_KERNEL_TRANSFER_ID=0
export CRITTER_COMM_KERNEL_TRANSFER_ID=0
export CRITTER_COMP_KERNEL_BUFFER_ID=0

export CRITTER_AUTOTUNING_DELTA=3

export CRITTER_AUTOTUNING_SAMPLE_CONSTRAINT_MODE=0

export CRITTER_PATTERN_ERROR_LIMIT=0.0625 #0.00390625 #0.0009765625
export CRITTER_VIZ_FILE=Test-${CRITTER_AUTOTUNING_TEST}__mechanism-${CRITTER_MECHANISM}_compr-${CRITTER_DECOMPOSITION_COMP_REPLACE}_commr-${CRITTER_DECOMPOSITION_COMM_REPLACE}_comm-ssam-${CRITTER_AUTOTUNING_COMM_STATE_AGGREGATION_MODE}_comp-ssam-${CRITTER_AUTOTUNING_COMP_STATE_AGGREGATION_MODE}_comm-kt-${CRITTER_COMM_KERNEL_TRANSFER_ID}_comp-kt-${CRITTER_COMP_KERNEL_TRANSFER_ID}_comp-kb-${CRITTER_COMP_KERNEL_BUFFER_ID}_scm-${CRITTER_AUTOTUNING_SAMPLE_CONSTRAINT_MODE}_d-${CRITTER_AUTOTUNING_DELTA}_el-${CRITTER_PATTERN_ERROR_LIMIT}
