#!/bin/bash

export CRITTER_TEST=baseline
export CRITTER_MECHANISM=0
#export CRITTER_TRACK_COLLECTIVE=1
#export CRITTER_TRACK_P2P=1
#export CRITTER_TRACK_BLAS=0
#export CRITTER_TRACK_LAPACK=0
#export CRITTER_SCHEDULE_KERNELS=1
export CRITTER_VIZ_FILE=${CRITTER_TEST}__mechanism-${CRITTER_MECHANISM}
