all:
	make -C./bench/qr/ cacqr2
	make -C./bench/cholesky/ cholinv
	make -C./bench/matmult/ summa3d

cacqr2:
	make -C./bench/qr/ cacqr2

cholinv:
	make -C./bench/cholesky/ cholinv

summa3d:
	make -C./bench/matmult/ summa3d

clean:
	make -C./bench/qr/ clean
	make -C./bench/cholesky/ clean
	make -C./bench/matmult/ clean
