cqr2_mpi:
	make -C./AlgebraicAlgorithms/QRFactorization/CholeskyQR2/ MPI

cfr3d_mpi:
	make -C./AlgebraicAlgorithms/CholeskyFactorization/CFR3D/ MPI

mm3d_mpi:
	make -C./AlgebraicAlgorithms/MatrixMultiplication/MM3D/ MPI

cqr2_ampi:
	make -C./AlgebraicAlgorithms/QRFactorization/CholeskyQR2/ AMPI

cfr3d_ampi:
	make -C./AlgebraicAlgorithms/CholeskyFactorization/CFR3D/ AMPI

mm3d_ampi:
	make -C./AlgebraicAlgorithms/MatrixMultiplication/MM3D/ AMPI

clean:
	make -C./AlgebraicAlgorithms/QRFactorization/CholeskyQR2/ clean
	make -C./AlgebraicAlgorithms/CholeskyFactorization/CFR3D/ clean
	make -C./AlgebraicAlgorithms/MatrixMultiplication/MM3D/ clean
